import type { GeneratedFile, ModuleStatusItem, ModuleStatusReport } from "@/lib/types"

type BuildProjectFilesInput = {
  prompt: string
  originalPrompt?: string | null
  projectName?: string | null
  providerMessage?: string | null
  promptSummary?: string | null
}

type BuildProjectFilesOutput = {
  message: string
  files: GeneratedFile[]
  moduleStatus: ModuleStatusReport
}

type BuildIntent = "dashboard" | "ecommerce" | "landing" | "portfolio" | "booking" | "crm" | "generic"

export function buildProjectFiles({
  prompt,
  originalPrompt,
  projectName,
  providerMessage,
  promptSummary,
}: BuildProjectFilesInput): BuildProjectFilesOutput {
  const name = sanitizeName(projectName || inferName(prompt) || "Swift Starter")
  const intent = inferBuildIntent(prompt)
  const brief = promptSummary || prompt
  const moduleStatus = buildModuleStatusReport({
    projectName: name,
    prompt: originalPrompt || prompt,
    intent,
    previewStatus: providerMessage ? "fallback" : "success",
  })

  const baseFiles = buildStandardStructureFiles(name)
  const domainOverrides =
    intent === "dashboard"
      ? buildDashboardOverrideFiles(name, brief)
      : intent === "ecommerce"
        ? buildCommerceOverrideFiles(name, brief)
        : intent === "landing"
          ? buildLandingOverrideFiles(name, brief)
          : intent === "portfolio"
            ? buildPortfolioOverrideFiles(name, brief)
            : intent === "booking"
              ? buildBookingOverrideFiles(name, brief)
              : intent === "crm"
                ? buildCrmOverrideFiles(name, brief)
                : buildGenericOverrideFiles(name, brief)

  const readme = buildReadmeFile({
    name,
    originalPrompt: originalPrompt || prompt,
    effectivePrompt: prompt,
    providerMessage,
  })

  const files = mergeFilesByPath([...baseFiles, readme], [
    ...domainOverrides,
    buildModuleStatusDataFile(moduleStatus),
  ])

  return {
    message: `Generated a full-stack ${intent} starter for ${name} using the standard Swift project tree.`,
    files,
    moduleStatus,
  }
}

function buildStandardStructureFiles(name: string): GeneratedFile[] {
  const safeName = serializeForCode(name)

  return [
    {
      path: "app/layout.tsx",
      language: "tsx",
      content: `import "./globals.css"

export const metadata = {
  title: ${safeName},
  description: "Generated by Swift Builder",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

export default function HomePage() {
  return (
    <main className="min-h-screen bg-neutral-950 px-6 py-20 text-white">
      <section className="mx-auto max-w-4xl rounded-3xl border border-white/10 bg-white/5 p-10">
        <h1 className="text-4xl font-semibold">Starter Project</h1>
        <p className="mt-4 text-neutral-300">Update this page from Code tab.</p>
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/globals.css",
      language: "css",
      content: `:root {
  --background: #0a0a0a;
  --foreground: #fafafa;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: var(--background);
  color: var(--foreground);
  font-family: Inter, system-ui, sans-serif;
}
`,
    },
    {
      path: "app/api/health/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export async function GET() {
  return NextResponse.json({ ok: true, service: "swift-generated-app" })
}
`,
    },
    {
      path: "app/api/generate/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => null)
  return NextResponse.json({ ok: true, received: body })
}
`,
    },
    {
      path: "app/api/projects/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export async function GET() {
  return NextResponse.json({ projects: [] })
}
`,
    },
    {
      path: "app/api/models/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export async function GET() {
  return NextResponse.json({
    models: [
      { key: "deepseek/deepseek-v4-flash", label: "Swift AI", provider: "openrouter", price: 2000 },
    ],
  })
}
`,
    },
    {
      path: "components/build-status-panel.tsx",
      language: "tsx",
      content: `import type { ModuleStatusItem, ModuleStatusReport } from "@/lib/build-status"

function StatusList({ title, items }: { title: string; items: ModuleStatusItem[] }) {
  if (items.length === 0) {
    return null
  }

  return (
    <section className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
      <h3 className="text-sm font-semibold text-white">{title}</h3>
      <ul className="mt-3 space-y-2">
        {items.map((item) => (
          <li key={item.name} className="rounded-lg bg-black/20 px-3 py-2">
            <p className="text-sm font-medium text-white">{item.name}</p>
            <p className="mt-1 text-xs text-neutral-400">{item.detail}</p>
          </li>
        ))}
      </ul>
    </section>
  )
}

export function BuildStatusPanel({ status }: { status: ModuleStatusReport }) {
  const tone =
    status.previewStatus === "success"
      ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-100"
      : status.previewStatus === "error"
        ? "border-rose-400/30 bg-rose-400/10 text-rose-100"
        : "border-amber-400/30 bg-amber-400/10 text-amber-100"

  return (
    <aside className="mx-auto mt-6 max-w-5xl rounded-2xl border border-white/10 bg-neutral-900/90 p-5 text-white shadow-2xl">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-xs uppercase tracking-[0.22em] text-neutral-400">Build Status</p>
          <h2 className="mt-2 text-2xl font-semibold">{status.projectName || "Generated Project"}</h2>
          <p className="mt-1 text-sm text-neutral-400">Current phase: {status.currentPhase}</p>
        </div>
        <span className={"w-fit rounded-full border px-3 py-1 text-xs font-medium " + tone}>
          Preview {status.previewStatus}
        </span>
      </div>

      <div className="mt-5 grid gap-4 lg:grid-cols-3">
        <StatusList title="Ready" items={status.ready} />
        <StatusList title="Partial" items={status.partial} />
        <StatusList title="Planned" items={status.planned} />
      </div>

      {status.errors.length > 0 && (
        <div className="mt-4">
          <StatusList title="Errors" items={status.errors} />
        </div>
      )}

      <section className="mt-4 rounded-xl border border-white/10 bg-white/[0.03] p-4">
        <h3 className="text-sm font-semibold text-white">Next Recommended Steps</h3>
        <ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-neutral-300">
          {status.nextSteps.map((step) => (
            <li key={step}>{step}</li>
          ))}
        </ol>
      </section>
    </aside>
  )
}
`,
    },
    {
      path: "components/ui/button.tsx",
      language: "tsx",
      content: `type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement>

export function Button({ className = "", ...props }: ButtonProps) {
  return (
    <button
      className={"inline-flex items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium text-black " + className}
      {...props}
    />
  )
}
`,
    },
    {
      path: "components/ui/card.tsx",
      language: "tsx",
      content: `export function Card({ children }: { children: React.ReactNode }) {
  return <div className="rounded-lg border border-white/10 bg-white/5 p-6">{children}</div>
}
`,
    },
    {
      path: "components/dashboard/sidebar.tsx",
      language: "tsx",
      content: `export function DashboardSidebar() {
  return (
    <aside className="w-64 border-r border-white/10 p-4 text-sm text-neutral-300">
      <p className="font-semibold text-white">Sidebar</p>
      <ul className="mt-4 space-y-2">
        <li>Dashboard</li>
        <li>Projects</li>
        <li>Settings</li>
      </ul>
    </aside>
  )
}
`,
    },
    {
      path: "components/editor/chat-panel.tsx",
      language: "tsx",
      content: `export function ChatPanel() {
  return <div className="rounded-lg border border-white/10 p-4">Chat Panel</div>
}
`,
    },
    {
      path: "components/editor/preview-panel.tsx",
      language: "tsx",
      content: `export function PreviewPanel() {
  return <div className="rounded-lg border border-white/10 p-4">Preview Panel</div>
}
`,
    },
    {
      path: "hooks/use-mobile.ts",
      language: "ts",
      content: `import { useEffect, useState } from "react"

export function useMobile(breakpoint = 768) {
  const [isMobile, setIsMobile] = useState(false)

  useEffect(() => {
    const update = () => setIsMobile(window.innerWidth < breakpoint)
    update()
    window.addEventListener("resize", update)
    return () => window.removeEventListener("resize", update)
  }, [breakpoint])

  return isMobile
}
`,
    },
    {
      path: "hooks/use-toast.ts",
      language: "ts",
      content: `type Toast = { title: string; description?: string }

export function useToast() {
  return {
    toast(toast: Toast) {
      console.log("toast", toast)
    },
  }
}
`,
    },
    {
      path: "lib/env.ts",
      language: "ts",
      content: `export const env = {
  nodeEnv: process.env.NODE_ENV || "development",
  tursoDatabaseUrl: process.env.TURSO_DATABASE_URL || "",
  tursoAuthToken: process.env.TURSO_AUTH_TOKEN || "",
  openRouterApiKey: process.env.OPENROUTER_API_KEY || "",
}
`,
    },
    {
      path: "lib/utils.ts",
      language: "ts",
      content: `export function cn(...parts: Array<string | false | null | undefined>) {
  return parts.filter(Boolean).join(" ")
}
`,
    },
    {
      path: "lib/store.ts",
      language: "ts",
      content: `type AppState = {
  activeProjectId: string | null
}

export const appStore: AppState = {
  activeProjectId: null,
}
`,
    },
    {
      path: "lib/ai/config.ts",
      language: "ts",
      content: `export const AI_CONFIG = {
  provider: "openrouter",
  model: "deepseek/deepseek-v4-flash",
  baseUrl: "https://openrouter.ai/api/v1",
  timeoutMs: Number(process.env.AI_TIMEOUT_MS || 60000),
}
`,
    },
    {
      path: "lib/ai/client.ts",
      language: "ts",
      content: `import { AI_CONFIG } from "./config"

export async function generateText(prompt: string) {
  return {
    provider: AI_CONFIG.provider,
    model: AI_CONFIG.model,
    message: "Generated response for: " + prompt,
  }
}
`,
    },
    {
      path: "lib/services/project.service.ts",
      language: "ts",
      content: `type Project = { id: string; name: string; updatedAt: string }

export function listProjects(): Project[] {
  return []
}
`,
    },
    {
      path: "prisma/schema.prisma",
      language: "prisma",
      content: `generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "sqlite"
  url      = env("TURSO_DATABASE_URL")
}

model Project {
  id        String   @id @default(cuid())
  name      String
  prompt    String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
`,
    },
    {
      path: "public/site.webmanifest",
      language: "json",
      content: `{
  "name": "Swift Generated App",
  "short_name": "SwiftApp",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#0a0a0a",
  "theme_color": "#0a0a0a"
}
`,
    },
    
    {
      path: ".env.example",
      language: "env",
      content: `TURSO_DATABASE_URL="libsql://your-turso-instance.turso.io"
    TURSO_AUTH_TOKEN="replace-me"
NEXTAUTH_SECRET="replace-me"
OPENROUTER_API_KEY="replace-me"
OPENROUTER_MAX_TOKENS="3000"
`,
    },
    {
      path: "auth.ts",
      language: "ts",
      content: `export const authConfig = {
  providers: ["credentials", "google"],
}
`,
    },
    {
      path: "components.json",
      language: "json",
      content: `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
`,
    },
    {
      path: "middleware.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export function middleware() {
  return NextResponse.next()
}
`,
    },
    {
      path: "next.config.mjs",
      language: "ts",
      content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    unoptimized: true,
  },
}

export default nextConfig
`,
    },
    {
      path: "package.json",
      language: "json",
      content: `{
  "name": "swift-generated-app",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "16.2.0",
    "react": "19.2.4",
    "react-dom": "19.2.4"
  },
  "devDependencies": {
    "typescript": "5.7.3"
  }
}
`,
    },
    {
      path: "postcss.config.mjs",
      language: "ts",
      content: `export default {
  plugins: {},
}
`,
    },
    {
      path: "tsconfig.json",
      language: "json",
      content: `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`,
    },
    {
      path: "styles/globals.css",
      language: "css",
      content: `/* global styles (no Tailwind) */
html, body { height: 100%; }
body { margin: 0; font-family: Inter, system-ui, sans-serif; }
`,
    }
  ]
}

function buildGenericOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-neutral-950 px-6 py-20 text-white">
      <section className="mx-auto max-w-4xl rounded-3xl border border-white/10 bg-white/5 p-10">
        <h1 className="text-4xl font-semibold">{projectName}</h1>
        <p className="mt-4 text-neutral-300">Build brief: {buildBrief}</p>
        <p className="mt-3 text-sm text-neutral-400">
          This output follows Swift standard structure: app, components, hooks, lib, prisma, public, styles.
        </p>
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
  ]
}

function buildDashboardOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const stats = [
  { label: "Revenue", value: "Rp 128.450.000", trend: "+12.4%" },
  { label: "Orders", value: "2,481", trend: "+8.1%" },
  { label: "Active Users", value: "9,204", trend: "+5.9%" },
  { label: "Conversion", value: "3.42%", trend: "+0.3%" },
]

const activities = [
  { title: "Invoice #INV-0324 paid", time: "2 minutes ago" },
  { title: "New user signed up", time: "9 minutes ago" },
  { title: "Project deployment completed", time: "23 minutes ago" },
  { title: "Payment method updated", time: "1 hour ago" },
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-neutral-950 text-white">
      <div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 md:grid-cols-[260px_1fr]">
        <aside className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <p className="text-xs uppercase tracking-[0.2em] text-emerald-300">Workspace</p>
          <h1 className="mt-3 text-2xl font-semibold">{projectName}</h1>
          <p className="mt-2 text-sm text-neutral-400">Dashboard fallback mode</p>
          <nav className="mt-6 space-y-2 text-sm text-neutral-300">
            <a className="block rounded-lg bg-white/10 px-3 py-2">Overview</a>
            <a className="block rounded-lg px-3 py-2 hover:bg-white/5">Analytics</a>
            <a className="block rounded-lg px-3 py-2 hover:bg-white/5">Projects</a>
            <a className="block rounded-lg px-3 py-2 hover:bg-white/5">Settings</a>
          </nav>
        </aside>

        <section className="space-y-6">
          <header className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <h2 className="text-2xl font-semibold">Dashboard Overview</h2>
            <p className="mt-2 text-sm text-neutral-300">Build brief: {buildBrief}</p>
          </header>

          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            {stats.map((item) => (
              <article key={item.label} className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
                <p className="text-xs uppercase tracking-wide text-neutral-400">{item.label}</p>
                <p className="mt-2 text-2xl font-semibold">{item.value}</p>
                <p className="mt-1 text-xs text-emerald-300">{item.trend}</p>
              </article>
            ))}
          </div>

          <article className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <h3 className="text-lg font-semibold">Recent Activity</h3>
            <ul className="mt-4 space-y-3 text-sm text-neutral-300">
              {activities.map((activity) => (
                <li key={activity.title} className="flex items-center justify-between rounded-lg bg-white/[0.02] px-3 py-2">
                  <span>{activity.title}</span>
                  <span className="text-xs text-neutral-500">{activity.time}</span>
                </li>
              ))}
            </ul>
          </article>
        </section>
        <BuildStatusPanel status={moduleStatus} />
      </div>
    </main>
  )
}
`,
    },
    {
      path: "app/api/dashboard/summary/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"
import { getDashboardSummary } from "@/lib/services/dashboard.service"

export async function GET() {
  const summary = await getDashboardSummary()
  return NextResponse.json(summary)
}
`,
    },
    {
      path: "lib/services/dashboard.service.ts",
      language: "ts",
      content: `export async function getDashboardSummary() {
  return {
    revenue: 128450000,
    orders: 2481,
    activeUsers: 9204,
    conversionRate: 3.42,
  }
}
`,
    },
  ]
}

function buildCommerceOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-neutral-950 px-6 py-16 text-white">
      <section className="mx-auto max-w-5xl rounded-3xl border border-white/10 bg-gradient-to-br from-orange-500/25 via-orange-600/10 to-neutral-900 p-10">
        <span className="rounded-full border border-orange-300/30 px-3 py-1 text-xs tracking-[0.2em] text-orange-200">
          {projectName}
        </span>
        <h1 className="mt-5 text-4xl font-semibold leading-tight">Build a modern commerce storefront</h1>
        <p className="mt-3 max-w-2xl text-neutral-300">Build brief: {buildBrief}</p>
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/api/products/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"
import { listProducts } from "@/lib/services/catalog.service"

export async function GET() {
  const products = await listProducts()
  return NextResponse.json({ products, total: products.length })
}
`,
    },
    {
      path: "app/api/orders/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const payload = await request.json()
  const customerName = payload?.customerName
  const items = payload?.items

  if (!customerName || !Array.isArray(items) || items.length === 0) {
    return NextResponse.json({ error: "customerName and items are required" }, { status: 400 })
  }

  return NextResponse.json({
    success: true,
    order: {
      id: "ord-" + Date.now(),
      customerName,
      itemCount: items.length,
      status: "pending-payment",
    },
  })
}
`,
    },
    {
      path: "lib/services/catalog.service.ts",
      language: "ts",
      content: `type Product = {
  id: string
  name: string
  price: number
  stock: number
}

const mockProducts: Product[] = [
  { id: "prod-1", name: "Starter Item", price: 149000, stock: 20 },
  { id: "prod-2", name: "Popular Item", price: 299000, stock: 50 },
  { id: "prod-3", name: "Premium Item", price: 499000, stock: 15 },
]

export async function listProducts(): Promise<Product[]> {
  return mockProducts
}
`,
    },
    {
      path: "prisma/schema.prisma",
      language: "prisma",
      content: `generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "sqlite"
  url      = env("TURSO_DATABASE_URL")
}

model Product {
  id          String   @id @default(cuid())
  name        String
  slug        String   @unique
  description String
  price       Int
  stock       Int
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}

model Order {
  id           String   @id @default(cuid())
  customerName String
  status       String   @default("pending-payment")
  totalAmount  Int
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}
`,
    },
  ]
}

function buildLandingOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const features = [
  "Conversion-focused hero with strong value proposition",
  "Social proof and trust indicators",
  "Clear call-to-action for demo or signup",
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-white text-slate-900">
      <header className="border-b border-slate-200 bg-white/90 backdrop-blur">
        <nav className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4">
          <p className="text-lg font-semibold">{projectName}</p>
          <a href="#cta" className="rounded-full bg-slate-900 px-4 py-2 text-sm font-medium text-white">Start Free</a>
        </nav>
      </header>
      <section className="mx-auto max-w-6xl px-4 py-16 md:py-24">
        <h1 className="max-w-3xl text-4xl font-bold tracking-tight md:text-6xl">Build trust fast and convert visitors into customers.</h1>
        <p className="mt-5 max-w-2xl text-base text-slate-600 md:text-lg">Build brief: {buildBrief}</p>
        <div className="mt-8 flex flex-wrap gap-3">
          <a id="cta" href="#" className="rounded-full bg-slate-900 px-5 py-3 text-sm font-medium text-white">Book a Demo</a>
          <a href="#" className="rounded-full border border-slate-300 px-5 py-3 text-sm font-medium text-slate-900">See Pricing</a>
        </div>
      </section>
      <section className="mx-auto grid max-w-6xl gap-4 px-4 pb-16 md:grid-cols-3">
        {features.map((item) => (
          <article key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-5">
            <h2 className="text-base font-semibold">{item}</h2>
          </article>
        ))}
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/api/leads/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const payload = await request.json()
  const email = payload?.email

  if (!email) {
    return NextResponse.json({ error: "email is required" }, { status: 400 })
  }

  return NextResponse.json({ ok: true, message: "Lead captured", email })
}
`,
    },
    {
      path: "lib/services/lead.service.ts",
      language: "ts",
      content: `type LeadInput = { email: string; source?: string }

export async function captureLead(input: LeadInput) {
  return {
    id: "lead-" + Date.now(),
    email: input.email,
    source: input.source || "landing-page",
  }
}
`,
    },
  ]
}

function buildPortfolioOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const projects = [
  { title: "Identity System Revamp", result: "+37% conversion" },
  { title: "SaaS Onboarding UX", result: "-42% drop-off" },
  { title: "B2B Dashboard Redesign", result: "+28 NPS" },
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-stone-50 text-stone-900">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-4 py-6">
        <p className="font-semibold">{projectName}</p>
        <a href="#contact" className="rounded-full bg-stone-900 px-4 py-2 text-sm text-white">Hire Me</a>
      </header>
      <section className="mx-auto max-w-6xl px-4 py-12 md:py-16">
        <p className="text-sm uppercase tracking-[0.2em] text-stone-500">Personal Brand Site</p>
        <h1 className="mt-4 max-w-3xl text-4xl font-bold md:text-6xl">Designing digital products that grow real business metrics.</h1>
        <p className="mt-5 max-w-2xl text-stone-600">Build brief: {buildBrief}</p>
      </section>
      <section className="mx-auto grid max-w-6xl gap-4 px-4 pb-16 md:grid-cols-3">
        {projects.map((project) => (
          <article key={project.title} className="rounded-2xl border border-stone-200 bg-white p-5">
            <h2 className="font-semibold">{project.title}</h2>
            <p className="mt-2 text-sm text-stone-600">{project.result}</p>
          </article>
        ))}
      </section>
      <footer id="contact" className="border-t border-stone-200 px-4 py-8 text-center text-sm text-stone-600">
        Ready to collaborate? Contact via portfolio inquiry form.
      </footer>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/api/inquiry/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const payload = await request.json()
  if (!payload?.name || !payload?.email) {
    return NextResponse.json({ error: "name and email are required" }, { status: 400 })
  }

  return NextResponse.json({ ok: true, status: "received" })
}
`,
    },
  ]
}

function buildBookingOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const slots = [
  { id: "slot-1", label: "Mon 09:00", available: true },
  { id: "slot-2", label: "Mon 11:00", available: false },
  { id: "slot-3", label: "Tue 14:00", available: true },
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}
  const availableSlots = slots.filter((slot) => slot.available)

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-10 text-slate-100 md:px-6">
      <header className="mx-auto flex w-full max-w-5xl items-center justify-between">
        <h1 className="text-2xl font-semibold">{projectName}</h1>
        <a href="#book" className="rounded-full bg-cyan-400 px-4 py-2 text-sm font-medium text-slate-950">Reserve Now</a>
      </header>
      <section className="mx-auto mt-8 w-full max-w-5xl rounded-2xl border border-white/10 bg-white/5 p-6">
        <h2 className="text-2xl font-semibold">Reservation System</h2>
        <p className="mt-2 text-sm text-slate-300">Build brief: {buildBrief}</p>
      </section>
      <section id="book" className="mx-auto mt-6 w-full max-w-5xl rounded-2xl border border-white/10 bg-white/5 p-6">
        <h3 className="text-lg font-medium">Available Slots</h3>
        {availableSlots.length === 0 ? (
          <p className="mt-4 text-sm text-slate-400">No slots available yet. Please check again later.</p>
        ) : (
          <ul className="mt-4 grid gap-3 sm:grid-cols-2">
            {availableSlots.map((slot) => (
              <li key={slot.id} className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">{slot.label}</li>
            ))}
          </ul>
        )}
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/api/bookings/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"
import { createBooking } from "@/lib/services/booking.service"

export async function POST(request: NextRequest) {
  const payload = await request.json()

  if (!payload?.customerName || !payload?.slotId) {
    return NextResponse.json({ error: "customerName and slotId are required" }, { status: 400 })
  }

  const booking = await createBooking(payload.customerName, payload.slotId)
  return NextResponse.json({ ok: true, booking })
}
`,
    },
    {
      path: "lib/services/booking.service.ts",
      language: "ts",
      content: `export async function createBooking(customerName: string, slotId: string) {
  return {
    id: "book-" + Date.now(),
    customerName,
    slotId,
    status: "confirmed",
  }
}
`,
    },
  ]
}

function buildCrmOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const leads = [
  { id: "lead-1", name: "Ari Putra", stage: "Qualified", value: "Rp 45.000.000" },
  { id: "lead-2", name: "Bina Group", stage: "Proposal", value: "Rp 120.000.000" },
  { id: "lead-3", name: "Citra Labs", stage: "Negotiation", value: "Rp 80.000.000" },
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-zinc-950 px-4 py-10 text-zinc-100 md:px-6">
      <header className="mx-auto flex w-full max-w-6xl items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">{projectName}</h1>
          <p className="mt-1 text-sm text-zinc-400">Internal CRM dashboard</p>
        </div>
        <a href="#" className="rounded-full bg-emerald-400 px-4 py-2 text-sm font-medium text-zinc-950">Add New Lead</a>
      </header>
      <section className="mx-auto mt-8 w-full max-w-6xl rounded-2xl border border-white/10 bg-white/5 p-6">
        <p className="text-sm text-zinc-300">Build brief: {buildBrief}</p>
      </section>
      <section className="mx-auto mt-6 w-full max-w-6xl rounded-2xl border border-white/10 bg-white/5 p-6">
        <h2 className="text-lg font-medium">Lead Pipeline</h2>
        {leads.length === 0 ? (
          <p className="mt-4 text-sm text-zinc-400">No leads yet. Start by adding your first opportunity.</p>
        ) : (
          <ul className="mt-4 space-y-3">
            {leads.map((lead) => (
              <li key={lead.id} className="flex flex-col gap-1 rounded-xl border border-white/10 bg-white/5 p-3 sm:flex-row sm:items-center sm:justify-between">
                <p className="font-medium">{lead.name}</p>
                <p className="text-sm text-zinc-300">{lead.stage}</p>
                <p className="text-sm text-emerald-300">{lead.value}</p>
              </li>
            ))}
          </ul>
        )}
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/api/leads/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"
import { listLeads, createLead } from "@/lib/services/crm.service"

export async function GET() {
  const leads = await listLeads()
  return NextResponse.json({ leads })
}

export async function POST(request: NextRequest) {
  const payload = await request.json()
  if (!payload?.name) {
    return NextResponse.json({ error: "name is required" }, { status: 400 })
  }

  const lead = await createLead(payload.name, payload.stage || "New")
  return NextResponse.json({ ok: true, lead })
}
`,
    },
    {
      path: "lib/services/crm.service.ts",
      language: "ts",
      content: `type Lead = {
  id: string
  name: string
  stage: string
}

const leadStore: Lead[] = [
  { id: "lead-1", name: "Acme Corp", stage: "Qualified" },
]

export async function listLeads(): Promise<Lead[]> {
  return leadStore
}

export async function createLead(name: string, stage: string): Promise<Lead> {
  const lead = { id: "lead-" + Date.now(), name, stage }
  leadStore.push(lead)
  return lead
}
`,
    },
  ]
}

function buildReadmeFile({
  name,
  originalPrompt,
  effectivePrompt,
  providerMessage,
}: {
  name: string
  originalPrompt: string
  effectivePrompt: string
  providerMessage?: string | null
}): GeneratedFile {
  return {
    path: "README.md",
    language: "md",
    content: `# ${escapeMultilineText(name)}

Generated with fixed Swift project structure.

## Included Root Tree

- app/
- components/
- hooks/
- lib/
- prisma/
- public/
- styles/
- .env.example
- auth.ts
- components.json
- middleware.ts
- next.config.mjs
- package.json
- postcss.config.mjs
- tsconfig.json

## Original Prompt

> ${escapeMultilineText(originalPrompt)}

## Effective Build Brief

${escapeMultilineText(effectivePrompt)}

## Provider Summary

${escapeMultilineText(providerMessage || "Local scaffold fallback was used.")}
`,
  }
}

export function buildModuleStatusReport({
  projectName,
  prompt,
  intent,
  previewStatus = "success",
  errorMessage,
}: {
  projectName?: string | null
  prompt: string
  intent?: BuildIntent
  previewStatus?: ModuleStatusReport["previewStatus"]
  errorMessage?: string | null
}): ModuleStatusReport {
  const normalized = prompt.toLowerCase()
  const inferredIntent = intent || inferBuildIntent(prompt)
  const ready: ModuleStatusItem[] = [
    {
      name: "Preview shell",
      status: "ready",
      detail: "A browser-safe page is available with mock data and visible build status.",
    },
    {
      name: "App Router structure",
      status: "ready",
      detail: "Core app, components, lib, prisma, public, and route handler folders are represented.",
    },
  ]
  const partial: ModuleStatusItem[] = []
  const planned: ModuleStatusItem[] = []
  const errors: ModuleStatusItem[] = []

  if (inferredIntent === "ecommerce" || /belanjaku|marketplace|shopee|seller|buyer|cart|checkout|midtrans/.test(normalized)) {
    ready.push({
      name: "Buyer storefront",
      status: "ready",
      detail: "Product-facing homepage and product API mock are included for preview.",
    })
    partial.push({
      name: "Cart and checkout engine",
      status: "partial",
      detail: "Checkout/order routes use mock payloads; payment provider integration is not connected yet.",
    })
    planned.push(
      {
        name: "Seller Center",
        status: "planned",
        detail: "Add product CRUD, order management, seller analytics, and settlement pages.",
      },
      {
        name: "Admin CMS",
        status: "planned",
        detail: "Add moderation queues, banner CMS, category management, and audit logs.",
      },
      {
        name: "Midtrans webhook",
        status: "planned",
        detail: "Connect signed payment notifications after env keys and database writes are ready.",
      }
    )
  } else if (inferredIntent === "dashboard") {
    ready.push({
      name: "Dashboard overview",
      status: "ready",
      detail: "KPI cards, activity feed, and summary route are available with mock metrics.",
    })
    partial.push({
      name: "Analytics detail",
      status: "partial",
      detail: "Overview data is mocked; drill-down charts and filters are planned.",
    })
  } else if (inferredIntent === "booking") {
    ready.push({
      name: "Booking preview",
      status: "ready",
      detail: "Available slots and booking route mock are included.",
    })
    partial.push({
      name: "Real scheduling rules",
      status: "partial",
      detail: "Calendar conflict checks and notifications still need database-backed logic.",
    })
  } else {
    partial.push({
      name: "Domain module",
      status: "partial",
      detail: "The first visible slice is ready; deeper business logic should be implemented in the next prompt.",
    })
  }

  planned.push({
    name: "Production data layer",
    status: "planned",
    detail: "Replace preview mock data with Prisma service calls once schema and env are finalized.",
  })

  if (previewStatus === "error" && errorMessage) {
    errors.push({
      name: "Preview error",
      status: "error",
      detail: errorMessage,
    })
  }

  return {
    projectName: projectName || undefined,
    previewStatus,
    currentPhase: inferCurrentPhase(inferredIntent, normalized),
    ready,
    partial,
    planned,
    errors,
    nextSteps: buildNextSteps(inferredIntent, normalized, previewStatus),
  }
}

function buildModuleStatusDataFile(status: ModuleStatusReport): GeneratedFile {
  return {
    path: "lib/build-status.ts",
    language: "ts",
    content: `export type ModuleStatusState = "ready" | "partial" | "planned" | "error"

export type ModuleStatusItem = {
  name: string
  status: ModuleStatusState
  detail: string
}

export type ModuleStatusReport = {
  projectName?: string
  previewStatus: "success" | "fallback" | "error"
  currentPhase: string
  ready: ModuleStatusItem[]
  partial: ModuleStatusItem[]
  planned: ModuleStatusItem[]
  errors: ModuleStatusItem[]
  nextSteps: string[]
}

export const moduleStatus: ModuleStatusReport = ${JSON.stringify(status, null, 2)}
`,
  }
}

function inferCurrentPhase(intent: BuildIntent, normalizedPrompt: string) {
  if (/seller|penjual/.test(normalizedPrompt)) return "seller-center"
  if (/admin|cms|moderation|moderasi/.test(normalizedPrompt)) return "admin-cms"
  if (/checkout|payment|midtrans|bayar|pembayaran/.test(normalizedPrompt)) return "checkout-payment"
  if (intent === "ecommerce") return "buyer-storefront"
  if (intent === "dashboard") return "dashboard-overview"
  if (intent === "booking") return "booking-flow"
  return "preview-first-foundation"
}

function buildNextSteps(intent: BuildIntent, normalizedPrompt: string, previewStatus: ModuleStatusReport["previewStatus"]) {
  if (previewStatus === "error") {
    return [
      "Fix the preview error shown in the status panel.",
      "Regenerate only the broken file after the preview renders.",
      "Continue with the next module once the shell is stable.",
    ]
  }

  if (intent === "ecommerce" || /belanjaku|marketplace|shopee/.test(normalizedPrompt)) {
    return [
      "Implement product CRUD for Seller Center.",
      "Connect cart state to checkout and order routes.",
      "Add Midtrans sandbox webhook with signature validation.",
      "Build Admin moderation for products, sellers, banners, and reports.",
    ]
  }

  return [
    "Turn the preview mock data into Prisma-backed services.",
    "Add the next user-facing flow as a small, testable module.",
    "Keep the build status panel updated after each generation.",
  ]
}

function mergeFilesByPath(base: GeneratedFile[], overrides: GeneratedFile[]) {
  const map = new Map<string, GeneratedFile>()

  for (const file of [...base, ...overrides]) {
    const normalizedPath = normalizePath(file.path)
    map.set(normalizedPath, {
      ...file,
      path: normalizedPath,
    })
  }

  return Array.from(map.values()).sort((a, b) => a.path.localeCompare(b.path))
}

function normalizePath(path: string) {
  return path.replace(/\\/g, "/").replace(/^\.\//, "")
}

function inferBuildIntent(prompt: string): BuildIntent {
  const normalized = prompt.toLowerCase()

  if (/(dashboard|admin|analytics|report|metric|kpi|sidebar)/i.test(normalized)) {
    return "dashboard"
  }

  if (/(marketplace|e-?commerce|shop|store|product|cart|checkout|shopee)/i.test(normalized)) {
    return "ecommerce"
  }

  if (/(landing page|landing|hero|marketing|cta|conversion)/i.test(normalized)) {
    return "landing"
  }

  if (/(portfolio|personal brand|resume|case study)/i.test(normalized)) {
    return "portfolio"
  }

  if (/(booking|reservation|appointment|schedule)/i.test(normalized)) {
    return "booking"
  }

  if (/(crm|lead|pipeline|sales ops|internal tool)/i.test(normalized)) {
    return "crm"
  }

  return "generic"
}

function inferName(prompt: string) {
  const quoted = prompt.match(/["“](.+?)["”]/)
  if (quoted?.[1]) return quoted[1]

  const named = prompt.match(/(?:named|bernama|name)\s+([a-z0-9][a-z0-9\\s-]{2,30})/i)
  if (named?.[1]) return named[1].trim()

  return null
}

function sanitizeName(input: string) {
  const normalized = input.replace(/\s+/g, " ").trim()
  return normalized.slice(0, 40)
}

function escapeInlineText(value: string) {
  return value
    .replace(/\s+/g, " ")
    .trim()
    .replace(/`/g, "'")
    .replace(/\$/g, "\\$")
}

function escapeMultilineText(value: string) {
  return value.replace(/`/g, "'").replace(/\$/g, "\\$")
}

function serializeForCode(value: string) {
  return JSON.stringify(value).replace(/\$/g, "\\$")
}
