export const TOPUP_MINIMUM_IDR = 2000
export const USD_TO_IDR = 15800
export const MIN_CRYPTO_PAYMENT_USD_CENTS = Math.ceil((TOPUP_MINIMUM_IDR / USD_TO_IDR) * 100)
export const MIN_CRYPTO_PAYMENT_USD = MIN_CRYPTO_PAYMENT_USD_CENTS / 100